### ISSUE TITLE
Public release checklist

### ISSUE THREAD

**Issue by mcginty** [tonarino/shadergraph#5]
- [x] Upstreamed glium PR is cut into release, see https://github.com/glium/glium/pull/1956#issuecomment-913591646 
- [x] Create an initial release version and tag on GitHub
- [x] `cargo publish`
- [x] Change repo visibility to public
- [x] Publish blog post
